Update docs
LM450N/toast-er pull request #24
Opened 2016-10-15 22:43 UTC by wincinderith

2016-10-15 23:32 UTC, LM450N commented
Maybe the documentation duplicated in the `readme` file must be removed. I tried to re-generate and publish the component page earlier but it fails. I don't know if the [tool](https://github.com/Polymer/tools/blob/master/bin/gp.sh) is till working...

2016-10-16 00:17 UTC, wincinderith commented
@LM450N The README should just link to the component page IMO.

2016-10-16 00:59 UTC, wincinderith commented
@LM450N Fixed everything I mentioned above.

2016-10-16 17:36 UTC, LM450N commented
I would like to solve the issue with the component page generator before merge this pull request. Simply because now the page is empty and the `README` is the only documentation available.

2016-10-17 09:19 UTC, wincinderith commented
@LM450N I'll send a PR for the component page as soon as this is merged, so the updated docs will be in it. I don't think it'll be an issue if there are no working docs for a max of 24 hours.

2016-10-17 09:48 UTC, LM450N commented
@wincinderith The component page is not broken, it's the generator of GitHub pages dedicated to Polymer elements. I don't know if we can fix it here because the "not found dependency" (in the console) is in the directory deployed on gitHub pages.

2016-10-17 10:35 UTC, wincinderith commented
I can fix it with a PR, trust me.

On Mon, 17 Oct 2016, 20:48 Mason Louchart <notifications@github.com> wrote:

> @wincinderith <https://github.com/wincinderith> The component page is not
> broken, it's the generator of GitHub pages dedicated to Polymer elements. I
> don't know if we can fix it here because the "not found dependency" (in the
> console) is in the directory deployed on gitHub pages.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/LM450N/toast-er/pull/24#issuecomment-254162429>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AMrbU3mh38yMyzMb886eKBC0Tt1b4wIhks5q00RagaJpZM4KX1bi>
> .
>

2016-10-18 10:14 UTC, masonlouchart requested changes
The command line to install the element must stay `bower install toast-er --save` because it's more explicit and understandable. People use shortcuts if they want.

2016-10-18 10:14 UTC, masonlouchart commented on README.md
> +  bower i -S toast-er
Beginners do not know the shortcuts. I think it's preferable to leave the command with explicit arguments.

2016-10-19 07:11 UTC, wincinderith commented
@LM450N Fixed!

2016-10-19 08:48 UTC, LM450N commented
LGTM

2016-10-19 08:48 UTC, masonlouchart approved these changes

2016-10-19 08:49 UTC, merged

2016-10-19 10:13 UTC, wincinderith commented
@LM450N I have a working [`gh-pages`](https://github.com/wincinderith/toast-er/tree/gh-pages) branch here. You'll need to pull this branch locally and do a forced push to your version of the branch, as the branches have a different commit history.

2016-10-19 10:41 UTC, LM450N commented
@wincinderith How have you generated this? I'm interesting to know to be able to do it myself for next releases.

2016-10-19 11:17 UTC, wincinderith commented
@LM450N Basically as follows in an empty directory on Unix:

    git clone https://github.com/Polymer/tools
    mkdir tmp && cd tmp
    ../tools/bin/gp.sh LM450N toast-er

You just need to make sure you have an SSH key setup on your system and
added to your GitHub account.

On Wed, 19 Oct 2016, 21:41 Mason Louchart <notifications@github.com> wrote:

> @wincinderith <https://github.com/wincinderith> How have you generated
> this? I'm interesting to know to be able to do it myself for next releases.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/LM450N/toast-er/pull/24#issuecomment-254777226>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AMrbUx5DHppS43_FGOcmQYvbobntdgcFks5q1fPkgaJpZM4KX1bi>
> .
>

2016-10-19 13:12 UTC, LM450N commented
@wincinderith I'm using the same tool but the result is not working 😞 ...